In [22]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)
import imageio
import csv

# Dog Example

In [7]:
img_arr = imageio.imread('./data/p1ch4/image-dog/bobby.jpg')
img_arr.shape

/var/folders/25/_xzr2f1s2yjgy1xmfcjypv8m0000gn/T/ipykernel_71036/2139723901.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('./data/p1ch4/image-dog/bobby.jpg')


(720, 1280, 3)

In [8]:
img_arr

array([[[ 77,  45,  22],
        [ 77,  45,  22],
        [ 78,  46,  21],
        ...,
        [118,  78,  52],
        [117,  77,  51],
        [116,  76,  50]],

       [[ 75,  43,  20],
        [ 76,  44,  21],
        [ 77,  45,  20],
        ...,
        [118,  78,  52],
        [117,  77,  51],
        [116,  76,  50]],

       [[ 74,  39,  17],
        [ 75,  40,  18],
        [ 77,  43,  18],
        ...,
        [117,  80,  51],
        [117,  78,  49],
        [116,  77,  48]],

       ...,

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [174, 121,  51],
        [176, 123,  53],
        [176, 123,  53]],

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [173, 123,  54],
        [174, 124,  55],
        [174, 124,  55]],

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [159, 109,  40],
        [158, 107,  41],
        [158, 107,  41]]

In [9]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

In [12]:
#out
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [13]:
batch

tensor([[[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]]],


        [[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]]],


        [[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
       

In [14]:
import os

data_dir = './data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3] # <1>
    batch[i] = img_t

/var/folders/25/_xzr2f1s2yjgy1xmfcjypv8m0000gn/T/ipykernel_71036/1155138954.py:7: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [16]:
batch = batch.float()
batch /= 255.0

In [17]:
batch

tensor([[[[0.6118, 0.5961,  ..., 0.5843, 0.6196],
          [0.6824, 0.5255,  ..., 0.5333, 0.5412],
          ...,
          [0.5059, 0.5098,  ..., 0.4745, 0.4471],
          [0.5059, 0.4824,  ..., 0.4745, 0.4706]],

         [[0.5451, 0.5294,  ..., 0.5294, 0.5765],
          [0.6275, 0.4667,  ..., 0.4784, 0.4863],
          ...,
          [0.4353, 0.4353,  ..., 0.4392, 0.4118],
          [0.4353, 0.4078,  ..., 0.4314, 0.4353]],

         [[0.5059, 0.4824,  ..., 0.5176, 0.5686],
          [0.6078, 0.4314,  ..., 0.4667, 0.4745],
          ...,
          [0.4235, 0.4235,  ..., 0.4588, 0.4314],
          [0.4196, 0.3843,  ..., 0.4510, 0.4549]]],


        [[[0.7922, 0.7569,  ..., 0.0510, 0.0471],
          [0.7804, 0.7529,  ..., 0.0549, 0.0549],
          ...,
          [0.2941, 0.2667,  ..., 0.1412, 0.1451],
          [0.3333, 0.4039,  ..., 0.1451, 0.1490]],

         [[0.5922, 0.5451,  ..., 0.0353, 0.0314],
          [0.5922, 0.5490,  ..., 0.0431, 0.0431],
          ...,
          [0.12

In [18]:
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [19]:
batch.shape

torch.Size([3, 3, 256, 256])

In [21]:
#batch

# Tabular Wine

In [24]:
wine_path = "./data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",
                         skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [26]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [27]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [28]:
data = wineq[:, :-1] # <1>
data, data.shape

(tensor([[ 7.0000,  0.2700,  ...,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  ...,  0.4900,  9.5000],
         ...,
         [ 5.5000,  0.2900,  ...,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  ...,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))