In [6]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)
import imageio
import csv

# Dog Example

In [2]:
img_arr = imageio.imread('./data/p1ch4/image-dog/bobby.jpg')
img_arr.shape

NameError: name 'imageio' is not defined

In [3]:
# converting the image to a 3x3 array 
img_arr

NameError: name 'img_arr' is not defined

In [4]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)
out

NameError: name 'torch' is not defined

In [12]:
#out
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [13]:
batch

tensor([[[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]]],


        [[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]]],


        [[[0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0],
          ...,
          [0, 0,  ..., 0, 0],
          [0, 0,  ..., 0, 0]],

         [[0, 0,  ..., 0, 0],
       

In [14]:
import os

data_dir = './data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3] # <1>
    batch[i] = img_t

/var/folders/25/_xzr2f1s2yjgy1xmfcjypv8m0000gn/T/ipykernel_71036/1155138954.py:7: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [16]:
batch = batch.float()
batch /= 255.0

In [17]:
batch

tensor([[[[0.6118, 0.5961,  ..., 0.5843, 0.6196],
          [0.6824, 0.5255,  ..., 0.5333, 0.5412],
          ...,
          [0.5059, 0.5098,  ..., 0.4745, 0.4471],
          [0.5059, 0.4824,  ..., 0.4745, 0.4706]],

         [[0.5451, 0.5294,  ..., 0.5294, 0.5765],
          [0.6275, 0.4667,  ..., 0.4784, 0.4863],
          ...,
          [0.4353, 0.4353,  ..., 0.4392, 0.4118],
          [0.4353, 0.4078,  ..., 0.4314, 0.4353]],

         [[0.5059, 0.4824,  ..., 0.5176, 0.5686],
          [0.6078, 0.4314,  ..., 0.4667, 0.4745],
          ...,
          [0.4235, 0.4235,  ..., 0.4588, 0.4314],
          [0.4196, 0.3843,  ..., 0.4510, 0.4549]]],


        [[[0.7922, 0.7569,  ..., 0.0510, 0.0471],
          [0.7804, 0.7529,  ..., 0.0549, 0.0549],
          ...,
          [0.2941, 0.2667,  ..., 0.1412, 0.1451],
          [0.3333, 0.4039,  ..., 0.1451, 0.1490]],

         [[0.5922, 0.5451,  ..., 0.0353, 0.0314],
          [0.5922, 0.5490,  ..., 0.0431, 0.0431],
          ...,
          [0.12

In [18]:
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [19]:
batch.shape

torch.Size([3, 3, 256, 256])

In [21]:
#batch

# Tabular Wine

In [24]:
wine_path = "./data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",
                         skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [26]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [27]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [28]:
data = wineq[:, :-1] # <1>
data, data.shape

(tensor([[ 7.0000,  0.2700,  ...,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  ...,  0.4900,  9.5000],
         ...,
         [ 5.5000,  0.2900,  ...,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  ...,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [29]:
target = wineq[:, -1] # <2>
target, target.shape

(tensor([6., 6.,  ..., 7., 6.]), torch.Size([4898]))

In [30]:
target = wineq[:, -1].long()
target

tensor([6, 6,  ..., 7, 6])

In [31]:
target_onehot = torch.zeros(target.shape[0], 10)

target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.],
        ...,
        [0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.]])

In [32]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

tensor([[6],
        [6],
        ...,
        [7],
        [6]])

In [33]:
data_mean = torch.mean(data, dim=0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [34]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [35]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.7208e-01, -8.1761e-02,  ..., -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  ...,  1.3422e-03, -8.2419e-01],
        ...,
        [-1.6054e+00,  1.1666e-01,  ..., -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  ..., -1.4882e+00,  1.0448e+00]])

In [36]:
bad_indexes = target <= 3 # <1>
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

In [37]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [38]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)] # <1>
good_data = data[target >= 7]

bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [39]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)

predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

In [40]:
actual_indexes = target > 5

actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [41]:
n_matches = torch.sum(actual_indexes & predicted_indexes).item()
n_predicted = torch.sum(predicted_indexes).item()
n_actual = torch.sum(actual_indexes).item()

n_matches, n_matches / n_predicted, n_matches / n_actual

(2018, 0.74000733406674, 0.6193984039287906)